-- =====================================================================
-- EOMS Supabase bridge schema
-- Paste this whole file into Supabase Dashboard -> SQL Editor -> Run.
-- It is idempotent: safe to re-run (tables are created only if missing,
-- policies/triggers are dropped and recreated, catalog seed skips existing keys).
--
-- Model: one table per app collection. The full app record lives in `data`
-- (jsonb); a few fields are "promoted" to real columns for filtering,
-- indexes and uniqueness. The app (js/services/localDb.js) writes both.
-- =====================================================================

-- ---------- updated_at trigger function ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- tables ----------
create table if not exists public.profiles (
  id           bigint generated by default as identity primary key,
  data         jsonb not null default '{}',
  created_at   timestamptz default now(),
  updated_at   timestamptz default now(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email        text unique,
  full_name    text,
  role         text constraint profiles_role_check check (role in ('admin','customer_care_manager','lead_engineer','operations')),
  status       text default 'ACTIVE' check (status in ('ACTIVE','SUSPENDED'))
);

create table if not exists public.ocular_inspections (
  id            bigint generated by default as identity primary key,
  data          jsonb not null default '{}',
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  rn_no         text unique,
  status        text,
  assigned_team bigint,
  created_by    bigint,
  deleted_at    timestamptz
);

create table if not exists public.installation_records (
  id              bigint generated by default as identity primary key,
  data            jsonb not null default '{}',
  created_at      timestamptz default now(),
  updated_at      timestamptz default now(),
  ocular_id       bigint,
  status          text,
  assigned_team   bigint,
  installation_no text,
  deleted_at      timestamptz
);

create table if not exists public.master_data_catalog (
  item_key   text primary key,
  data       jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  category   text
);

create table if not exists public.photo_attachments (
  id         bigint generated by default as identity primary key,
  data       jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id         bigint generated by default as identity primary key,
  data       jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  category   text,
  severity   text,
  actor_id   bigint
);

create table if not exists public.support_tickets (
  id         bigint generated by default as identity primary key,
  data       jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  status     text,
  created_by bigint
);

create table if not exists public.sales_leads (
  id            bigint generated by default as identity primary key,
  data          jsonb not null default '{}',
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  stage         text,
  legacy_row_id text unique,
  ocular_id     bigint unique,
  deleted_at    timestamptz
);

create table if not exists public.notifications (
  id         bigint generated by default as identity primary key,
  data       jsonb not null default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  user_id    bigint,
  is_read    boolean default false
);

-- ---------- indexes on promoted filter columns ----------
create index if not exists profiles_role_idx                 on public.profiles (role);
create index if not exists profiles_status_idx               on public.profiles (status);
create index if not exists ocular_inspections_status_idx     on public.ocular_inspections (status);
create index if not exists ocular_inspections_team_idx       on public.ocular_inspections (assigned_team);
create index if not exists ocular_inspections_created_by_idx on public.ocular_inspections (created_by);
create index if not exists ocular_inspections_deleted_idx    on public.ocular_inspections (deleted_at);
create index if not exists installation_records_ocular_idx   on public.installation_records (ocular_id);
create index if not exists installation_records_status_idx   on public.installation_records (status);
create index if not exists installation_records_team_idx     on public.installation_records (assigned_team);
create index if not exists installation_records_no_idx       on public.installation_records (installation_no);
create index if not exists installation_records_deleted_idx  on public.installation_records (deleted_at);
create index if not exists master_data_catalog_category_idx  on public.master_data_catalog (category);
create index if not exists audit_logs_category_idx           on public.audit_logs (category);
create index if not exists audit_logs_severity_idx           on public.audit_logs (severity);
create index if not exists audit_logs_actor_idx              on public.audit_logs (actor_id);
create index if not exists support_tickets_status_idx        on public.support_tickets (status);
create index if not exists support_tickets_created_by_idx    on public.support_tickets (created_by);
create index if not exists sales_leads_stage_idx             on public.sales_leads (stage);
create index if not exists sales_leads_deleted_idx           on public.sales_leads (deleted_at);
create index if not exists notifications_user_idx            on public.notifications (user_id);
create index if not exists notifications_is_read_idx         on public.notifications (is_read);

-- ---------- updated_at triggers ----------
do $$
declare t text;
begin
  foreach t in array array['profiles','ocular_inspections','installation_records','master_data_catalog',
                           'photo_attachments','audit_logs','support_tickets','sales_leads','notifications']
  loop
    execute format('drop trigger if exists set_updated_at on public.%I', t);
    execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()', t);
  end loop;
end $$;

-- ---------- role helper (security definer: bypasses RLS on profiles) ----------
create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles
  where auth_user_id = auth.uid() and status = 'ACTIVE'
  limit 1;
$$;

revoke all on function public.current_app_role() from public;
grant execute on function public.current_app_role() to authenticated;

-- ---------- Row Level Security ----------
-- All tables except profiles: any signed-in user (role authenticated) has full access.
-- anon (not signed in) gets nothing: no policy grants it anything.
do $$
declare t text;
begin
  foreach t in array array['ocular_inspections','installation_records','master_data_catalog',
                           'photo_attachments','audit_logs','support_tickets','sales_leads','notifications']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on public.%I', t);
    execute format('create policy "authenticated full access" on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- profiles: everyone signed in can read; only admins can insert/update/delete.
alter table public.profiles enable row level security;
drop policy if exists "profiles select authenticated" on public.profiles;
drop policy if exists "profiles insert admin"         on public.profiles;
drop policy if exists "profiles update admin"         on public.profiles;
drop policy if exists "profiles delete admin"         on public.profiles;
create policy "profiles select authenticated" on public.profiles
  for select to authenticated using (true);
create policy "profiles insert admin" on public.profiles
  for insert to authenticated with check (public.current_app_role() = 'admin');
create policy "profiles update admin" on public.profiles
  for update to authenticated using (public.current_app_role() = 'admin')
  with check (public.current_app_role() = 'admin');
create policy "profiles delete admin" on public.profiles
  for delete to authenticated using (public.current_app_role() = 'admin');

-- ---------- Realtime ----------
-- Adds tables to the realtime publication, skipping any already added so re-runs do not error.
do $$
declare t text;
begin
  foreach t in array array['notifications','ocular_inspections','installation_records','sales_leads','support_tickets']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- ---------- Seed: master data catalog (137 items) ----------
-- NOTE: currentStock and unitPrice values below are PLACEHOLDERS carried over
-- from the demo seed. The lead engineer must correct prices/stock before they
-- are relied on for quotes or inventory. Existing rows are NOT overwritten on re-run.
insert into public.master_data_catalog (item_key, category, data) values
  ('item-0', 'breakers', '{"category":"breakers","itemKey":"item-0","itemName":"ABB 40A S/N:BLY1200655-Breaker","details":{},"currentStock":196,"unitPrice":1024}'::jsonb),
  ('item-1', 'breakers', '{"category":"breakers","itemKey":"item-1","itemName":"ABB Bolt on Circuit Breaker TQC2440WL 40A 2P","details":{},"currentStock":164,"unitPrice":1114}'::jsonb),
  ('item-2', 'hardware', '{"category":"hardware","itemKey":"item-2","itemName":"ABB S202-C2 400V 6000 3 2B","details":{},"currentStock":12,"unitPrice":1396}'::jsonb),
  ('item-3', 'enclosures', '{"category":"enclosures","itemKey":"item-3","itemName":"ANDELI ADB3LE-63 6000A 230V - 50/60HZ","details":{},"currentStock":215,"unitPrice":529}'::jsonb),
  ('item-4', 'hardware', '{"category":"hardware","itemKey":"item-4","itemName":"Atlanta PVC Solvent cement C#0032670","details":{},"currentStock":67,"unitPrice":837}'::jsonb),
  ('item-5', 'hardware', '{"category":"hardware","itemKey":"item-5","itemName":"Bass bar","details":{},"currentStock":159,"unitPrice":1234}'::jsonb),
  ('item-6', 'hardware', '{"category":"hardware","itemKey":"item-6","itemName":"BM 125SN 125AT, 3P, 30KAIC@ 230V","details":{},"currentStock":184,"unitPrice":1196}'::jsonb),
  ('item-7', 'hardware', '{"category":"hardware","itemKey":"item-7","itemName":"Bottom Knot  3/8","details":{},"currentStock":60,"unitPrice":895}'::jsonb),
  ('item-8', 'breakers', '{"category":"breakers","itemKey":"item-8","itemName":"Breaker MCBB","details":{},"currentStock":159,"unitPrice":748}'::jsonb),
  ('item-9', 'breakers', '{"category":"breakers","itemKey":"item-9","itemName":"BREAKER SLEMENS 2W/240 3VM 3VM1010- 3ED32-0AA0","details":{},"currentStock":33,"unitPrice":1016}'::jsonb),
  ('item-10', 'hardware', '{"category":"hardware","itemKey":"item-10","itemName":"BUTANE GAS Johnson Electic 250 UN 2037","details":{},"currentStock":173,"unitPrice":1306}'::jsonb),
  ('item-11', 'wires', '{"category":"wires","itemKey":"item-11","itemName":"CABLE LUG  ELA LUG0503 SCHNEIDER ELECTRIC . 13 PER PACK","details":{},"currentStock":9,"unitPrice":1129}'::jsonb),
  ('item-12', 'hardware', '{"category":"hardware","itemKey":"item-12","itemName":"CAUTION TAPE","details":{},"currentStock":90,"unitPrice":1315}'::jsonb),
  ('item-13', 'enclosures', '{"category":"enclosures","itemKey":"item-13","itemName":"CHNT  DB-2F808044 BC#624","details":{},"currentStock":263,"unitPrice":1256}'::jsonb),
  ('item-14', 'breakers', '{"category":"breakers","itemKey":"item-14","itemName":"Circuit Breaker Plug in 10LA 120/240 V 40A","details":{},"currentStock":74,"unitPrice":1276}'::jsonb),
  ('item-15', 'fittings', '{"category":"fittings","itemKey":"item-15","itemName":"CLAMP 1/2 2HOLE","details":{},"currentStock":70,"unitPrice":1303}'::jsonb),
  ('item-16', 'fittings', '{"category":"fittings","itemKey":"item-16","itemName":"CLAMP 3/4  1HOLE","details":{},"currentStock":4,"unitPrice":1143}'::jsonb),
  ('item-17', 'fittings', '{"category":"fittings","itemKey":"item-17","itemName":"CLAMP 3/4  2HOLE","details":{},"currentStock":275,"unitPrice":126}'::jsonb),
  ('item-18', 'conduits', '{"category":"conduits","itemKey":"item-18","itemName":"CONDUIT THREADED  TYPE 3/4\" T","details":{},"currentStock":128,"unitPrice":761}'::jsonb),
  ('item-19', 'conduits', '{"category":"conduits","itemKey":"item-19","itemName":"CONDUIT THREADED LR TYPE 3/4\" LR","details":{},"currentStock":95,"unitPrice":1355}'::jsonb),
  ('item-20', 'hardware', '{"category":"hardware","itemKey":"item-20","itemName":"Connection End B/(M41) 2.0 # 236120","details":{},"currentStock":107,"unitPrice":1399}'::jsonb),
  ('item-21', 'conduits', '{"category":"conduits","itemKey":"item-21","itemName":"Connector 1/2\" EMT SET SCREW","details":{},"currentStock":217,"unitPrice":275}'::jsonb),
  ('item-22', 'hardware', '{"category":"hardware","itemKey":"item-22","itemName":"COVER 4 x8x8","details":{},"currentStock":50,"unitPrice":543}'::jsonb),
  ('item-23', 'hardware', '{"category":"hardware","itemKey":"item-23","itemName":"CTE AS2500/5A 5VA-CL05 50/60 HZ","details":{},"currentStock":215,"unitPrice":1480}'::jsonb),
  ('item-24', 'wires', '{"category":"wires","itemKey":"item-24","itemName":"CTE YL PE CABLE APUT-36C1X1-T","details":{},"currentStock":130,"unitPrice":974}'::jsonb),
  ('item-25', 'hardware', '{"category":"hardware","itemKey":"item-25","itemName":"D 14mm BLUE","details":{},"currentStock":133,"unitPrice":1511}'::jsonb),
  ('item-26', 'hardware', '{"category":"hardware","itemKey":"item-26","itemName":"D 14mm YELLOW","details":{},"currentStock":95,"unitPrice":939}'::jsonb),
  ('item-27', 'hardware', '{"category":"hardware","itemKey":"item-27","itemName":"D 14mm YELLOW","details":{},"currentStock":116,"unitPrice":849}'::jsonb),
  ('item-28', 'hardware', '{"category":"hardware","itemKey":"item-28","itemName":"D 14mmGREEN","details":{},"currentStock":144,"unitPrice":1282}'::jsonb),
  ('item-29', 'hardware', '{"category":"hardware","itemKey":"item-29","itemName":"D 30m BLUE","details":{},"currentStock":90,"unitPrice":715}'::jsonb),
  ('item-30', 'hardware', '{"category":"hardware","itemKey":"item-30","itemName":"D 30m RED","details":{},"currentStock":82,"unitPrice":622}'::jsonb),
  ('item-31', 'enclosures', '{"category":"enclosures","itemKey":"item-31","itemName":"DISTRIBUTION BOX MCGILL 6WAYS","details":{},"currentStock":289,"unitPrice":735}'::jsonb),
  ('item-32', 'wires', '{"category":"wires","itemKey":"item-32","itemName":"DURAFLEX 5.5 150/roll GREEN","details":{},"currentStock":2,"unitPrice":1117}'::jsonb),
  ('item-33', 'wires', '{"category":"wires","itemKey":"item-33","itemName":"DURAFLEX 8.0 150 m/roll RED","details":{},"currentStock":245,"unitPrice":1366}'::jsonb),
  ('item-34', 'wires', '{"category":"wires","itemKey":"item-34","itemName":"DURAFLEX 8.0 150 m/roll YELLOW","details":{},"currentStock":13,"unitPrice":1304}'::jsonb),
  ('item-35', 'wires', '{"category":"wires","itemKey":"item-35","itemName":"DURAFLEX 8.00mm GREEN","details":{},"currentStock":172,"unitPrice":932}'::jsonb),
  ('item-36', 'hardware', '{"category":"hardware","itemKey":"item-36","itemName":"ELBOW 1 1/2\"","details":{},"currentStock":96,"unitPrice":1221}'::jsonb),
  ('item-37', 'hardware', '{"category":"hardware","itemKey":"item-37","itemName":"ELBOW 1\"","details":{},"currentStock":90,"unitPrice":1428}'::jsonb),
  ('item-38', 'hardware', '{"category":"hardware","itemKey":"item-38","itemName":"ELECTRIC METER  51952734","details":{},"currentStock":157,"unitPrice":1359}'::jsonb),
  ('item-39', 'hardware', '{"category":"hardware","itemKey":"item-39","itemName":"ELECTRIC METER SAFARI","details":{},"currentStock":272,"unitPrice":932}'::jsonb),
  ('item-40', 'hardware', '{"category":"hardware","itemKey":"item-40","itemName":"Electrical Tape","details":{},"currentStock":31,"unitPrice":1399}'::jsonb),
  ('item-41', 'conduits', '{"category":"conduits","itemKey":"item-41","itemName":"EMT PIPE 3/4 \" MCGILL","details":{},"currentStock":87,"unitPrice":891}'::jsonb),
  ('item-42', 'conduits', '{"category":"conduits","itemKey":"item-42","itemName":"EMT SET SCREW COUPLING  1/2\" MCGILL","details":{},"currentStock":106,"unitPrice":410}'::jsonb),
  ('item-43', 'conduits', '{"category":"conduits","itemKey":"item-43","itemName":"EMT SET SCREW COUPLING  3/4\" MCGILL","details":{},"currentStock":234,"unitPrice":655}'::jsonb),
  ('item-44', 'conduits', '{"category":"conduits","itemKey":"item-44","itemName":"EMTSET SCRE CONNECTOR 3/4\"  MCGILL","details":{},"currentStock":10,"unitPrice":962}'::jsonb),
  ('item-45', 'hardware', '{"category":"hardware","itemKey":"item-45","itemName":"Fiber Glass Mesh Tape","details":{},"currentStock":189,"unitPrice":560}'::jsonb),
  ('item-46', 'hardware', '{"category":"hardware","itemKey":"item-46","itemName":"FULL TRADE 3/8\"","details":{},"currentStock":208,"unitPrice":1441}'::jsonb),
  ('item-47', 'breakers', '{"category":"breakers","itemKey":"item-47","itemName":"GE Circuit Breaker Plug In 7QL244 Bolt on  40 A 2P","details":{},"currentStock":9,"unitPrice":650}'::jsonb),
  ('item-48', 'breakers', '{"category":"breakers","itemKey":"item-48","itemName":"GE Circuit Breaker TQC3440 WL 30A 3P","details":{},"currentStock":280,"unitPrice":811}'::jsonb),
  ('item-49', 'hardware', '{"category":"hardware","itemKey":"item-49","itemName":"GRINDING DESK (PANGHASA)","details":{},"currentStock":111,"unitPrice":321}'::jsonb),
  ('item-50', 'hardware', '{"category":"hardware","itemKey":"item-50","itemName":"GROUNDING ROD","details":{},"currentStock":262,"unitPrice":584}'::jsonb),
  ('item-51', 'hardware', '{"category":"hardware","itemKey":"item-51","itemName":"HIGH GRADE LENGTHTEN ALLOY HOLE SAW W3722-20 20MM","details":{},"currentStock":49,"unitPrice":468}'::jsonb),
  ('item-52', 'conduits', '{"category":"conduits","itemKey":"item-52","itemName":"IMC COUPLING 1/2\"","details":{},"currentStock":123,"unitPrice":856}'::jsonb),
  ('item-53', 'conduits', '{"category":"conduits","itemKey":"item-53","itemName":"IMC Coupling Connector MCGILL","details":{},"currentStock":244,"unitPrice":1428}'::jsonb),
  ('item-54', 'conduits', '{"category":"conduits","itemKey":"item-54","itemName":"IMC PIPE 1\"  MCGILL","details":{},"currentStock":269,"unitPrice":763}'::jsonb),
  ('item-55', 'conduits', '{"category":"conduits","itemKey":"item-55","itemName":"IMC PIPE 1/2\"  MCGILL","details":{},"currentStock":228,"unitPrice":1095}'::jsonb),
  ('item-56', 'conduits', '{"category":"conduits","itemKey":"item-56","itemName":"IMC PIPE 3/4\"  MCGILL","details":{},"currentStock":179,"unitPrice":522}'::jsonb),
  ('item-57', 'enclosures', '{"category":"enclosures","itemKey":"item-57","itemName":"JUNCTION BOX","details":{},"currentStock":179,"unitPrice":496}'::jsonb),
  ('item-58', 'enclosures', '{"category":"enclosures","itemKey":"item-58","itemName":"JUNCTION BOX  COVER","details":{},"currentStock":181,"unitPrice":173}'::jsonb),
  ('item-59', 'enclosures', '{"category":"enclosures","itemKey":"item-59","itemName":"JUNON Distribution Box 6ways 230v/400v, 63a/p40  model #DX10-A06SWB","details":{},"currentStock":100,"unitPrice":329}'::jsonb),
  ('item-60', 'hardware', '{"category":"hardware","itemKey":"item-60","itemName":"KOTEN CB 40A","details":{},"currentStock":60,"unitPrice":179}'::jsonb),
  ('item-61', 'hardware', '{"category":"hardware","itemKey":"item-61","itemName":"KOTEN CB K63NC 32 220/380V10AA  / EC60898","details":{},"currentStock":38,"unitPrice":597}'::jsonb),
  ('item-62', 'fittings', '{"category":"fittings","itemKey":"item-62","itemName":"LIQUID TIGHT CONNECTOR  1 1/4\"","details":{},"currentStock":205,"unitPrice":56}'::jsonb),
  ('item-63', 'conduits', '{"category":"conduits","itemKey":"item-63","itemName":"LL 1/2  Thread Conduit Bodies Series w/cover MCGILL","details":{},"currentStock":24,"unitPrice":685}'::jsonb),
  ('item-64', 'conduits', '{"category":"conduits","itemKey":"item-64","itemName":"LQT 1/2\" HOSE","details":{},"currentStock":11,"unitPrice":687}'::jsonb),
  ('item-65', 'conduits', '{"category":"conduits","itemKey":"item-65","itemName":"LQT 3/4\" HOSE","details":{},"currentStock":67,"unitPrice":662}'::jsonb),
  ('item-66', 'conduits', '{"category":"conduits","itemKey":"item-66","itemName":"LQT Connector 1/2","details":{},"currentStock":176,"unitPrice":569}'::jsonb),
  ('item-67', 'conduits', '{"category":"conduits","itemKey":"item-67","itemName":"LQT Connector 3/4 MCGILL","details":{},"currentStock":228,"unitPrice":1053}'::jsonb),
  ('item-68', 'conduits', '{"category":"conduits","itemKey":"item-68","itemName":"LQT Connector 3/4\"","details":{},"currentStock":73,"unitPrice":1436}'::jsonb),
  ('item-69', 'conduits', '{"category":"conduits","itemKey":"item-69","itemName":"LQT STRAIGHT CONNECTOR 3/4\"","details":{},"currentStock":195,"unitPrice":269}'::jsonb),
  ('item-70', 'breakers', '{"category":"breakers","itemKey":"item-70","itemName":"MCB 20AT, 2P, 230V RPCH2P","details":{},"currentStock":149,"unitPrice":615}'::jsonb),
  ('item-71', 'breakers', '{"category":"breakers","itemKey":"item-71","itemName":"MCCB 80AT, 3P, 400V BM100HBN","details":{},"currentStock":12,"unitPrice":894}'::jsonb),
  ('item-72', 'breakers', '{"category":"breakers","itemKey":"item-72","itemName":"MCCB14 2PAC460V BF52a20A","details":{},"currentStock":23,"unitPrice":1361}'::jsonb),
  ('item-73', 'enclosures', '{"category":"enclosures","itemKey":"item-73","itemName":"MCGILL 4WAYS DB 200X 130X 100mm","details":{},"currentStock":75,"unitPrice":1393}'::jsonb),
  ('item-74', 'enclosures', '{"category":"enclosures","itemKey":"item-74","itemName":"MCGILL Waterproof  Distribution Box w/ DIN RAIL&screws 230-273-110m MGWDB-12","details":{},"currentStock":73,"unitPrice":439}'::jsonb),
  ('item-75', 'breakers', '{"category":"breakers","itemKey":"item-75","itemName":"MEGA HIMEL Breaker HDB9LEN63A26405 2P6RA 40A","details":{},"currentStock":109,"unitPrice":265}'::jsonb),
  ('item-76', 'conduits', '{"category":"conduits","itemKey":"item-76","itemName":"Metalic Conduit 3/4\"","details":{},"currentStock":275,"unitPrice":1105}'::jsonb),
  ('item-77', 'breakers', '{"category":"breakers","itemKey":"item-77","itemName":"METASOL MCCB ABN103C A3P","details":{},"currentStock":110,"unitPrice":552}'::jsonb),
  ('item-78', 'hardware', '{"category":"hardware","itemKey":"item-78","itemName":"MICA TUBE 1/2","details":{},"currentStock":241,"unitPrice":945}'::jsonb),
  ('item-79', 'breakers', '{"category":"breakers","itemKey":"item-79","itemName":"MINIATURE CIRCUIT BREAKER MCB BHA3LC20 IP20A 6KAAC240V SHIHLIN","details":{},"currentStock":196,"unitPrice":423}'::jsonb),
  ('item-80', 'hardware', '{"category":"hardware","itemKey":"item-80","itemName":"Pako 3\"","details":{},"currentStock":52,"unitPrice":1043}'::jsonb),
  ('item-81', 'hardware', '{"category":"hardware","itemKey":"item-81","itemName":"PANASONIC CB / EC60898-1 415V C40 BB122402CWTB","details":{},"currentStock":205,"unitPrice":235}'::jsonb),
  ('item-82', 'wires', '{"category":"wires","itemKey":"item-82","itemName":"PD 1.25m WHITE","details":{},"currentStock":118,"unitPrice":485}'::jsonb),
  ('item-83', 'wires', '{"category":"wires","itemKey":"item-83","itemName":"PD 100m YELLOW","details":{},"currentStock":71,"unitPrice":681}'::jsonb),
  ('item-84', 'wires', '{"category":"wires","itemKey":"item-84","itemName":"PD 125m BLUE","details":{},"currentStock":18,"unitPrice":100}'::jsonb),
  ('item-85', 'wires', '{"category":"wires","itemKey":"item-85","itemName":"PD 125m RED","details":{},"currentStock":296,"unitPrice":214}'::jsonb),
  ('item-86', 'wires', '{"category":"wires","itemKey":"item-86","itemName":"PD 125mYELLOW","details":{},"currentStock":228,"unitPrice":385}'::jsonb),
  ('item-87', 'wires', '{"category":"wires","itemKey":"item-87","itemName":"PD 22 BLUE","details":{},"currentStock":203,"unitPrice":521}'::jsonb),
  ('item-88', 'wires', '{"category":"wires","itemKey":"item-88","itemName":"PD 22 RED","details":{},"currentStock":208,"unitPrice":128}'::jsonb),
  ('item-89', 'wires', '{"category":"wires","itemKey":"item-89","itemName":"PD 22 YELLOW","details":{},"currentStock":246,"unitPrice":1255}'::jsonb),
  ('item-90', 'wires', '{"category":"wires","itemKey":"item-90","itemName":"PD 3.5 BLUE","details":{},"currentStock":288,"unitPrice":916}'::jsonb),
  ('item-91', 'wires', '{"category":"wires","itemKey":"item-91","itemName":"PD 3.5 YELLOW","details":{},"currentStock":17,"unitPrice":1529}'::jsonb),
  ('item-92', 'wires', '{"category":"wires","itemKey":"item-92","itemName":"PD 30m  WHITE","details":{},"currentStock":158,"unitPrice":776}'::jsonb),
  ('item-93', 'wires', '{"category":"wires","itemKey":"item-93","itemName":"PD 30m BLUE","details":{},"currentStock":24,"unitPrice":1397}'::jsonb),
  ('item-94', 'wires', '{"category":"wires","itemKey":"item-94","itemName":"PD 30m RED","details":{},"currentStock":262,"unitPrice":741}'::jsonb),
  ('item-95', 'wires', '{"category":"wires","itemKey":"item-95","itemName":"PD 30m YELLOW","details":{},"currentStock":149,"unitPrice":165}'::jsonb),
  ('item-96', 'wires', '{"category":"wires","itemKey":"item-96","itemName":"PD 38mm WHITE","details":{},"currentStock":212,"unitPrice":212}'::jsonb),
  ('item-97', 'wires', '{"category":"wires","itemKey":"item-97","itemName":"PD 5.5 BLUE","details":{},"currentStock":268,"unitPrice":187}'::jsonb),
  ('item-98', 'wires', '{"category":"wires","itemKey":"item-98","itemName":"PD 5.5 RED","details":{},"currentStock":176,"unitPrice":1307}'::jsonb),
  ('item-99', 'wires', '{"category":"wires","itemKey":"item-99","itemName":"PD 5.5 YELLOW","details":{},"currentStock":21,"unitPrice":1278}'::jsonb),
  ('item-100', 'wires', '{"category":"wires","itemKey":"item-100","itemName":"PD 8.0 RED","details":{},"currentStock":126,"unitPrice":631}'::jsonb),
  ('item-101', 'wires', '{"category":"wires","itemKey":"item-101","itemName":"PD 8.0 YELLOW","details":{},"currentStock":242,"unitPrice":1503}'::jsonb),
  ('item-102', 'hardware', '{"category":"hardware","itemKey":"item-102","itemName":"PF 38mm WHITE","details":{},"currentStock":270,"unitPrice":768}'::jsonb),
  ('item-103', 'hardware', '{"category":"hardware","itemKey":"item-103","itemName":"PLASTIC MOLDING  3/4 GRAY","details":{},"currentStock":195,"unitPrice":1444}'::jsonb),
  ('item-104', 'hardware', '{"category":"hardware","itemKey":"item-104","itemName":"PLASTIC MOLDING  3/4 WHITE","details":{},"currentStock":65,"unitPrice":1323}'::jsonb),
  ('item-105', 'wires', '{"category":"wires","itemKey":"item-105","itemName":"POWER FLEX 8.0m RED","details":{},"currentStock":231,"unitPrice":410}'::jsonb),
  ('item-106', 'wires', '{"category":"wires","itemKey":"item-106","itemName":"POWERFLEX  14mm BLUE","details":{},"currentStock":26,"unitPrice":710}'::jsonb),
  ('item-107', 'wires', '{"category":"wires","itemKey":"item-107","itemName":"POWERFLEX  14mm RED","details":{},"currentStock":12,"unitPrice":1271}'::jsonb),
  ('item-108', 'wires', '{"category":"wires","itemKey":"item-108","itemName":"POWERFLEX  5.5 WHITE","details":{},"currentStock":289,"unitPrice":1274}'::jsonb),
  ('item-109', 'wires', '{"category":"wires","itemKey":"item-109","itemName":"POWERFLEX  5.5 YELLOW","details":{},"currentStock":135,"unitPrice":139}'::jsonb),
  ('item-110', 'wires', '{"category":"wires","itemKey":"item-110","itemName":"POWERFLEX  8.0 GREEN","details":{},"currentStock":292,"unitPrice":214}'::jsonb),
  ('item-111', 'wires', '{"category":"wires","itemKey":"item-111","itemName":"POWERFLEX 5.5 BLUE","details":{},"currentStock":250,"unitPrice":1130}'::jsonb),
  ('item-112', 'wires', '{"category":"wires","itemKey":"item-112","itemName":"POWERFLEX 5.5m RED","details":{},"currentStock":19,"unitPrice":185}'::jsonb),
  ('item-113', 'enclosures', '{"category":"enclosures","itemKey":"item-113","itemName":"Pullbox  6\"x8\"x8\" GA # 18","details":{},"currentStock":226,"unitPrice":328}'::jsonb),
  ('item-114', 'conduits', '{"category":"conduits","itemKey":"item-114","itemName":"PVC Pipe 1/2\" ATLANTA","details":{},"currentStock":296,"unitPrice":753}'::jsonb),
  ('item-115', 'conduits', '{"category":"conduits","itemKey":"item-115","itemName":"PVC Pipe 3/4\" ATLANTA","details":{},"currentStock":10,"unitPrice":1239}'::jsonb),
  ('item-116', 'breakers', '{"category":"breakers","itemKey":"item-116","itemName":"\"RCBO 2P 40at BHL B32 40AT 2P\"","details":{},"currentStock":277,"unitPrice":1378}'::jsonb),
  ('item-117', 'breakers', '{"category":"breakers","itemKey":"item-117","itemName":"RCBO SHIHLIN BHL 33 3P 400/415V C40","details":{},"currentStock":299,"unitPrice":106}'::jsonb),
  ('item-118', 'breakers', '{"category":"breakers","itemKey":"item-118","itemName":"RESIDUAL CURRENT CIRCUIT BREAKER WITH OVER CURRENT PROTECTION BHL33C 32AT, 3P, 400V","details":{},"currentStock":143,"unitPrice":872}'::jsonb),
  ('item-119', 'hardware', '{"category":"hardware","itemKey":"item-119","itemName":"SAMSUNG 60 inside 10W DL120","details":{},"currentStock":271,"unitPrice":80}'::jsonb),
  ('item-120', 'hardware', '{"category":"hardware","itemKey":"item-120","itemName":"Screw  124000014178","details":{},"currentStock":103,"unitPrice":1028}'::jsonb),
  ('item-121', 'enclosures', '{"category":"enclosures","itemKey":"item-121","itemName":"SELHOT SHOW-6 WATERPROOF DB 1P66","details":{},"currentStock":235,"unitPrice":355}'::jsonb),
  ('item-122', 'hardware', '{"category":"hardware","itemKey":"item-122","itemName":"SHIHLIN BML32 230/240V C40 G","details":{},"currentStock":81,"unitPrice":569}'::jsonb),
  ('item-123', 'breakers', '{"category":"breakers","itemKey":"item-123","itemName":"SHIHLIN MCCB BM100-ABN 4P 80A w/accessories","details":{},"currentStock":158,"unitPrice":890}'::jsonb),
  ('item-124', 'hardware', '{"category":"hardware","itemKey":"item-124","itemName":"SHIHLIN PHL 33   400LY15V-C32","details":{},"currentStock":76,"unitPrice":345}'::jsonb),
  ('item-125', 'hardware', '{"category":"hardware","itemKey":"item-125","itemName":"Smoke Test","details":{},"currentStock":158,"unitPrice":137}'::jsonb),
  ('item-126', 'enclosures', '{"category":"enclosures","itemKey":"item-126","itemName":"SQUARE BOX","details":{},"currentStock":213,"unitPrice":1191}'::jsonb),
  ('item-127', 'enclosures', '{"category":"enclosures","itemKey":"item-127","itemName":"SQUARE BOX COVER","details":{},"currentStock":159,"unitPrice":844}'::jsonb),
  ('item-128', 'hardware', '{"category":"hardware","itemKey":"item-128","itemName":"TOX SCREW 8\"","details":{},"currentStock":228,"unitPrice":1527}'::jsonb),
  ('item-129', 'fittings', '{"category":"fittings","itemKey":"item-129","itemName":"UNIT STRUT CLAMP 3/4\" MCGILL","details":{},"currentStock":137,"unitPrice":1212}'::jsonb),
  ('item-130', 'enclosures', '{"category":"enclosures","itemKey":"item-130","itemName":"UTILITY BOX","details":{},"currentStock":171,"unitPrice":736}'::jsonb),
  ('item-131', 'conduits', '{"category":"conduits","itemKey":"item-131","itemName":"YL /  \"LB\" 1/2\"  Straight Threaded Conduit Bodies Series w/coverMCGIL","details":{},"currentStock":160,"unitPrice":1297}'::jsonb),
  ('item-132', 'conduits', '{"category":"conduits","itemKey":"item-132","itemName":"YL /  \"LB\" 1/2\" Threaded Conduit Bodies Series w/cover MCGIL","details":{},"currentStock":93,"unitPrice":119}'::jsonb),
  ('item-133', 'conduits', '{"category":"conduits","itemKey":"item-133","itemName":"YL /  \"LB\" 3/4\"  Straight Threaded Conduit Bodies Series w/cover MCGIL","details":{},"currentStock":125,"unitPrice":480}'::jsonb),
  ('item-134', 'hardware', '{"category":"hardware","itemKey":"item-134","itemName":"YOKOHAMA Transformer 380-400-440x","details":{},"currentStock":289,"unitPrice":1478}'::jsonb),
  ('item-135', 'breakers', '{"category":"breakers","itemKey":"item-135","itemName":"BM250CN3P125A: SHIHLIN B250-CN 3P125A MCCB INDUSTRIAL","details":{},"currentStock":107,"unitPrice":1456}'::jsonb),
  ('item-136', 'hardware', '{"category":"hardware","itemKey":"item-136","itemName":"SHTBM250SNAC220V: SHIHLIN SHUNT TRIP FOR BM250SN/HN","details":{},"currentStock":160,"unitPrice":347}'::jsonb)
on conflict (item_key) do nothing;
